### ISSUE TITLE
Webpack version conflict on npm start

### ISSUE THREAD

**Issue by zvone** [softberry/timemanager#50]
When trying to run the app with `npm start` on a fresh pull it fails because of a webpack version conflict depicted below.

![image](https://user-images.githubusercontent.com/3396790/73882934-4e3ffd00-4863-11ea-9979-480dcc36e91d.png)

The issue is caused by the `react-scripts` version being fixed to `3.2.0`.

Setting it to `^3.3.1` fixed the issue for me.

BR
Zvonimir :)

**Comment by softberry** [comment]
Hi @zvone , 
thanks for the warning. Use ``yarn`` instead instead of ``npm``. I did not have time to have a proper readme until now.
